<?php

/**
 * PluginioMediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginioMediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginioMediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginioMedia');
    }
}